//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloqLab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloqLab.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik jest popsuty..
        /// </summary>
        internal static string CannotLoadFile {
            get {
                return ResourceManager.GetString("CannotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blok decyzji.
        /// </summary>
        internal static string DecisiveBlockName {
            get {
                return ResourceManager.GetString("DecisiveBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemat ma już jeden blok startowy..
        /// </summary>
        internal static string MessageBoxAlreadyOneStopBlock {
            get {
                return ResourceManager.GetString("MessageBoxAlreadyOneStopBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe rozszerzenie pliku..
        /// </summary>
        internal static string MessageBoxBadExtensionMessage {
            get {
                return ResourceManager.GetString("MessageBoxBadExtensionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blok operacyjny.
        /// </summary>
        internal static string OperatingBlockName {
            get {
                return ResourceManager.GetString("OperatingBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string StartBlockName {
            get {
                return ResourceManager.GetString("StartBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string StopBlockName {
            get {
                return ResourceManager.GetString("StopBlockName", resourceCulture);
            }
        }
    }
}
